// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: checkTokenExpired.sql

package database

import (
	"context"
)

const checkTokenExpired = `-- name: CheckTokenExpired :exec
SELECT expires_at
FROM refresh_tokens
WHERE token = $1
AND expires < NOW()
`

func (q *Queries) CheckTokenExpired(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, checkTokenExpired, token)
	return err
}
