// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deleteChirp.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteChirp = `-- name: DeleteChirp :execrows
DELETE FROM chirps
WHERE id = $1
AND user_id = $2
`

type DeleteChirpParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteChirp(ctx context.Context, arg DeleteChirpParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteChirp, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
