// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: getTokenExpiresRevokeByToken.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const getTokenExpiresRevokeByToken = `-- name: GetTokenExpiresRevokeByToken :one
SELECT token, expires_at, revoked_at, user_id
FROM refresh_tokens
WHERE token = $1
`

type GetTokenExpiresRevokeByTokenRow struct {
	Token     string
	ExpiresAt time.Time
	RevokedAt sql.NullTime
	UserID    uuid.UUID
}

func (q *Queries) GetTokenExpiresRevokeByToken(ctx context.Context, token string) (GetTokenExpiresRevokeByTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getTokenExpiresRevokeByToken, token)
	var i GetTokenExpiresRevokeByTokenRow
	err := row.Scan(
		&i.Token,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserID,
	)
	return i, err
}
