// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: insertEmailPassword.sql

package database

import (
	"context"
)

const insertUser = `-- name: InsertUser :exec
INSERT INTO users (email, hashed_password)
VALUES ($1, $2)
`

type InsertUserParams struct {
	Email          string
	HashedPassword string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.ExecContext(ctx, insertUser, arg.Email, arg.HashedPassword)
	return err
}
