// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: updateUserData.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updateUserData = `-- name: UpdateUserData :exec
UPDATE users
SET
    email = $2,
    updated_at = NOW(),
    hashed_password = $3
WHERE id = $1
`

type UpdateUserDataParams struct {
	ID             uuid.UUID
	Email          string
	HashedPassword string
}

func (q *Queries) UpdateUserData(ctx context.Context, arg UpdateUserDataParams) error {
	_, err := q.db.ExecContext(ctx, updateUserData, arg.ID, arg.Email, arg.HashedPassword)
	return err
}
