// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: updateJWT.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updateJWT = `-- name: UpdateJWT :exec
UPDATE refresh_tokens
SET
    token = $2,
    updated_at = NOW(),
    expires_at = NOW() + INTERVAL '1 hour',
    revoked_at = NULL
WHERE user_id = $1
`

type UpdateJWTParams struct {
	UserID uuid.UUID
	Token  string
}

func (q *Queries) UpdateJWT(ctx context.Context, arg UpdateJWTParams) error {
	_, err := q.db.ExecContext(ctx, updateJWT, arg.UserID, arg.Token)
	return err
}
